package repositories

import (
	"context"
	"database/sql"
	"fmt"

	"arcmilestone/models"
)

// ApplicationRepository contains persistence operations for job applications.
// Business rules such as deadline checks, creator-cannot-apply, and
// accept-only-one belong to the service layer.
type ApplicationRepository struct {
	db *sql.DB
}

// CreateApplicationParams contains the fields required to insert a new
// application. The job's funded escrow amount is the payment; freelancers
// apply for the fixed amount set by the client and do not propose a counter-amount.
// The database generates id, status defaults to 'pending', and timestamps
// are generated by MySQL.
type CreateApplicationParams struct {
	JobID           uint64
	ApplicantUserID uint64
	CoverLetter     string
	EstimatedDays   uint32
	PortfolioURL    *string
}

const applicationColumns = `
	id,
	job_id,
	applicant_user_id,
	cover_letter,
	estimated_days,
	portfolio_url,
	status,
	created_at,
	updated_at`

// NewApplicationRepository constructs a repository using an existing connection pool.
func NewApplicationRepository(db *sql.DB) *ApplicationRepository {
	return &ApplicationRepository{db: db}
}

// Create inserts a new application row and returns the database-generated ID.
// The UNIQUE(job_id, applicant_user_id) constraint is the final protection
// against duplicate applications; a duplicate insert will surface as a driver error.
func (r *ApplicationRepository) Create(ctx context.Context, params CreateApplicationParams) (uint64, error) {
	result, err := r.db.ExecContext(ctx, `
		INSERT INTO applications (
			job_id,
			applicant_user_id,
			cover_letter,
			estimated_days,
			portfolio_url
		) VALUES (?, ?, ?, ?, ?)`,
		params.JobID,
		params.ApplicantUserID,
		params.CoverLetter,
		params.EstimatedDays,
		params.PortfolioURL,
	)
	if err != nil {
		return 0, fmt.Errorf("create application: %w", err)
	}

	lastID, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("read created application ID: %w", err)
	}
	if lastID < 0 {
		return 0, fmt.Errorf("read created application ID: database returned a negative ID")
	}

	return uint64(lastID), nil
}

// FindByID returns an application by its internal database ID. A missing row
// is returned as a wrapped sql.ErrNoRows.
func (r *ApplicationRepository) FindByID(ctx context.Context, id uint64) (*models.Application, error) {
	app, err := scanApplication(r.db.QueryRowContext(ctx,
		"SELECT "+applicationColumns+" FROM applications WHERE id = ?",
		id,
	))
	if err != nil {
		return nil, fmt.Errorf("find application by ID: %w", err)
	}

	return app, nil
}

// ListByJob returns all applications for a given job, ordered oldest first so
// that the earliest applicants are naturally surfaced at the top.
func (r *ApplicationRepository) ListByJob(ctx context.Context, jobID uint64) ([]*models.Application, error) {
	rows, err := r.db.QueryContext(ctx,
		"SELECT "+applicationColumns+`
		FROM applications
		WHERE job_id = ?
		ORDER BY created_at ASC, id ASC`,
		jobID,
	)
	if err != nil {
		return nil, fmt.Errorf("list applications by job: %w", err)
	}
	defer rows.Close()

	return collectApplications(rows)
}

// ListByApplicant returns all applications submitted by a given user, newest first.
func (r *ApplicationRepository) ListByApplicant(ctx context.Context, applicantUserID uint64) ([]*models.Application, error) {
	rows, err := r.db.QueryContext(ctx,
		"SELECT "+applicationColumns+`
		FROM applications
		WHERE applicant_user_id = ?
		ORDER BY created_at DESC, id DESC`,
		applicantUserID,
	)
	if err != nil {
		return nil, fmt.Errorf("list applications by applicant: %w", err)
	}
	defer rows.Close()

	return collectApplications(rows)
}

// FindByJobAndApplicant returns the application for a specific job/applicant
// pair. It exists so the service layer can check whether a user already applied
// before attempting an insert. A missing row returns a wrapped sql.ErrNoRows.
func (r *ApplicationRepository) FindByJobAndApplicant(ctx context.Context, jobID, applicantUserID uint64) (*models.Application, error) {
	app, err := scanApplication(r.db.QueryRowContext(ctx,
		"SELECT "+applicationColumns+`
		FROM applications
		WHERE job_id = ?
		  AND applicant_user_id = ?`,
		jobID,
		applicantUserID,
	))
	if err != nil {
		return nil, fmt.Errorf("find application by job and applicant: %w", err)
	}

	return app, nil
}

// UpdateStatus changes the status of a single application. Valid status values
// are defined by the models.ApplicationStatus constants; the ENUM column rejects
// invalid strings at the database level.
func (r *ApplicationRepository) UpdateStatus(ctx context.Context, applicationID uint64, status models.ApplicationStatus) error {
	result, err := r.db.ExecContext(ctx, `
		UPDATE applications
		SET status = ?
		WHERE id = ?`,
		status,
		applicationID,
	)
	if err != nil {
		return fmt.Errorf("update application status: %w", err)
	}

	return requireOneAffectedRow(ctx, r.db, "applications", applicationID, result, "update application status")
}

func collectApplications(rows *sql.Rows) ([]*models.Application, error) {
	apps := make([]*models.Application, 0)
	for rows.Next() {
		app, err := scanApplication(rows)
		if err != nil {
			return nil, fmt.Errorf("scan application row: %w", err)
		}
		apps = append(apps, app)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate application rows: %w", err)
	}

	return apps, nil
}

func scanApplication(row rowScanner) (*models.Application, error) {
	a := new(models.Application)
	if err := row.Scan(
		&a.ID,
		&a.JobID,
		&a.ApplicantUserID,
		&a.CoverLetter,
		&a.EstimatedDays,
		&a.PortfolioURL,
		&a.Status,
		&a.CreatedAt,
		&a.UpdatedAt,
	); err != nil {
		return nil, err
	}

	return a, nil
}
